### ISSUE TITLE
EPIC 0.1

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/SensorUtils#100]
1. As a user, I would like a command line tool that takes in an ISD and returns the phase, emission, and ra/dec for a given location on the ground and a given pixel location in the image.

Desired Artifacts:
- [ ] Shared Library on OS X/Linux
- [ ] SET executable
- [ ] Design documentation showing the class hierarchy
- [ ] Activity diagrams (where appropriate) to illustrate the separation of modules

2. As a user, I would like to be able to accurately run image2Ground and ground2Image using the CTX camera model.

Desired Artifacts:
- [ ] usgscsm.so for linux and OS X
- [ ] tests in the source code

3. As a user, I would like to utilize the SWIG wrappers on an external library.
- [ ] publicly available SWIG wrapper
- [ ] Example iPython notebook

**Comment by jlaura** [comment]
For 3.  I have opened:

https://github.com/USGS-Astrogeology/CSM-Swig/issues/1
https://github.com/USGS-Astrogeology/CSM-Swig/issues/2

This work is completely doable in the week. I do not have many sub-issues to open on these because the tasks are quite atomic.

**Comment by jessemapel** [comment]
@thareUSGS For 2, do we have stuff to check against? Should we just use ISIS images or are there values that JPL has verified that we are going to use?

**Comment by thareUSGS** [comment]
Activity diagram for phase, activity diagram for Sensor construction.

**Comment by thareUSGS** [comment]
(2) usgscsm.so for linux and OS X -- needs to be broken into multiple tasks
